# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d617b9016d292227689993ca464a9cc2ad7785475de6b3e66e648f6db0ca5e964d6d458a2a918d4094d17dd0561a291da17a2d5fe92e809fb1a0c29c13f9cea3

test:
  secret_key_base: ec680fbb06fc464d8efcccb74f6a4f1a3f4f92a5f24a008e54cae1098a10fd259e6fff44a1a44599e97aac5cc8304830ae08bd8b342b8d9d159201057bdb5277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
